f = open("Source.txt", 'r')
poz = f.readline()
poz = poz[:-1]

Final = f.readline().split()
L = f.readline().split()
Adjacency = {}

while L:
    if L[0] not in Adjacency.keys():
        Adjacency[L[0]] = [[L[1], L[2]]]

    else:
        Adjacency[L[0]].append([L[1], L[2]])
    L = f.readline().split()


Word = input("The word is: ")

StateSet = []
StateSetChange = []
StateSet.append(poz)

if Word == '':
    if poz in Final:
        print("The word can be generated by this grammar.")
    else:
        print("The word cannot be generated by this grammar.")
else:
    Counter = 0
    for i in Word:
        Counter += 1
        for State in StateSet:
            if State in Adjacency:
                for Arc in Adjacency[State]:
                    if i == Arc[1]:
                        if Counter == len(Word) and Arc[0] == "*":
                            StateSetChange.append(State)
                        elif Counter < len(Word) and Arc[0] == "*":
                            Arc[1] = '~'
                        elif Arc[0] != '*':
                            StateSetChange.append(Arc[0])
        StateSet = StateSetChange
        StateSetChange = []

Found = False
for State in Final:
    if State in StateSet:
        print("The word can be generated by this grammar.")
        Found = True
        break
if Found == False:
    print("The word cannot be generated by this grammar.")

print(Adjacency)